---
# file: site.yml
- hosts: all
  user: '{{ user }}'
  sudo: yes
  roles:
    - base

#- include bt-tracker.yml
#- include dbservers.yml
#- include domain-controllers.yml
#- include fileservers.yml
#- include: loadbalancers.yml
#- include webservers.yml
