---
# file: roles/loadbalancers/handlers/main.yml
    - name: start haproxy
      service: name=haproxy state=started enabled=true

    - name: reload haproxy
      service: name=haproxy state=reloaded

    - name: update apt cache
      apt: update_cache=yes
